title: "My World"
author: KA HOU CHAN
email: kahou76@uw.edu
theme: minima
description: hiiii

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
